require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
    NewCops: enable

# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

# Metrics ---------------------------------------------------------------------

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 6

# Layout ----------------------------------------------------------------------

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true

# RSpec -----------------------------------------------------------------------

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 14

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 3
